[package]
name = "primint"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Abstraction over the primitive integer types"
repository.workspace = true
license.workspace = true
keywords = ["integer", "num-traits", "primitive"]
categories = ["data-structures", "no-std", "no-std::no-alloc", "rust-patterns"]

[package.metadata.docs.rs]
all-features = true

[dependencies]
bytemuck = { version = "1", optional = true }
num-traits-02 = { package = "num-traits", version = "0.2", optional = true }
serde = { package = "serde_core", version = "1", optional = true }

[features]
default = ["nonmax", "nonzero"]
# Have PrimitiveInt extend bytemuck::{Contiguous, Pod}
bytemuck = ["dep:bytemuck"]
# Define NonMax<T>, generic over PrimitiveInt (requires nonzero feature)
nonmax = ["nonzero"]
# Define NonZero<T> generic over PrimitiveInt
nonzero = []
# Have PrimitiveInt extend num_traits::PrimInt (v0.2)
num-traits-02 = ["dep:num-traits-02"]
# Have PrimitiveInt extend serde::{Serialize, DeserializeOwned}
serde = ["dep:serde"]
